### PR TITLE
Update WoWPro_Profession_Parser.lua

### PR DESCRIPTION
**Pull request by Spoony36**
Slightly Reword profession parser as i think it would look better in the profession guides

image

Reject if needed and you'd prefer to leave as is

### CODE REVIEW

**Comment by Blanckaert** [comment]
Yeah, reason I had "crafting" was a hope that we could get it to automate.  But that is something that is not being figured out (any time soon[tm])

**Comment by Spoony36** [comment]
Oh so it would auto update that text like 
crafting up to 60
crafting up to 59
crafting up to 58 etc?

That would be a nice feature tbh

**Comment by Ludovicus-Maior** [comment]
Oh, I think I had a patch to do that that I never finished debugging...
Sigh.

**Comment by Spoony36** [comment]
I'm just wondering if the wording needs tweaking then

image

Should it maybe say 

Craft these from Cooking level 1 to 40 (You may need to craft up 60 to achieve this)

**Comment by Ludovicus-Maior** [comment]
Discuss with @Blanckaert .  When you both agree, a pull request can be submitted.
I rarely get involved with wording issues as English is not my first language.

**Pull request merged**
