### PR TITLE
Update WoWPro_Profession_Vanilla.toc

### PR DESCRIPTION
**Pull request by Spoony36**
Remove Professions\Guides.xml as no longer valid

### CODE REVIEW

**Comment by Ludovicus-Maior** [comment]
@Spoony36 This leaves no Professions in the  Retail Professions guide at all!
Are you sure?

**Comment by Spoony36** [comment]
This is for Vanilla isn't it?

Will still load guides from this ? Vanilla\Guides.xml

**Comment by Ludovicus-Maior** [comment]
Vanilla stil has professions.

**Comment by Spoony36** [comment]
> Vanilla stil has professions. And I dont see a load for `Vanilla\Guides.xml`

Bottom line in TOC?

**Comment by Ludovicus-Maior** [comment]
I am an idiot!

**Pull request merged**
